"""initial schema

Revision ID: 8dacf31e8c5b
Revises: 
Create Date: 2026-02-18 11:31:15.257477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8dacf31e8c5b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.Column('actor_role', sa.String(length=32), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('document_types',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extraction_template', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('field_definitions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_routing', sa.String(length=32), nullable=True),
    sa.Column('language_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_types_code'), 'document_types', ['code'], unique=True)
    op.create_table('engine_configs',
    sa.Column('engine_name', sa.String(length=64), nullable=False),
    sa.Column('adapter_type', sa.String(length=64), nullable=False),
    sa.Column('deployment_mode', sa.Enum('HOSTED_API', 'SELF_HOSTED', name='deploymentmode'), nullable=False),
    sa.Column('endpoint_url', sa.String(length=512), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('api_key_encrypted', sa.String(length=1024), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('data_sovereignty_ack', sa.Boolean(), nullable=False),
    sa.Column('cost_tracking_enabled', sa.Boolean(), nullable=False),
    sa.Column('health_status', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('tracking_id', sa.String(length=64), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('dpi', sa.Integer(), nullable=True),
    sa.Column('preproc_quality', sa.Float(), nullable=True),
    sa.Column('classification', sa.String(length=128), nullable=True),
    sa.Column('class_confidence', sa.Float(), nullable=True),
    sa.Column('document_type_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PREPROCESSING', 'CLASSIFYING', 'EXTRACTING', 'COMPLETED', 'FAILED', 'REVIEW_REQUIRED', name='documentstatus'), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_tracking_id'), 'documents', ['tracking_id'], unique=True)
    op.create_table('extraction_results',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('engine_used', sa.String(length=64), nullable=False),
    sa.Column('engine_version', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('structured_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('field_confidences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('aggregate_confidence', sa.Float(), nullable=True),
    sa.Column('classification', sa.String(length=128), nullable=True),
    sa.Column('routing_decision', sa.String(length=32), nullable=True),
    sa.Column('processing_ms', sa.Integer(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_results_document_id'), 'extraction_results', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extraction_results_document_id'), table_name='extraction_results')
    op.drop_table('extraction_results')
    op.drop_index(op.f('ix_documents_tracking_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('engine_configs')
    op.drop_index(op.f('ix_document_types_code'), table_name='document_types')
    op.drop_table('document_types')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
