import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='JsonExt', default=dict)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='DateCreated', null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_column='DateUpdated', null=True)),
                ('version', models.IntegerField(default=1)),
                ('validity_from', models.DateTimeField(blank=True, db_column='ValidityFrom', null=True)),
                ('validity_to', models.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('extraction_template', models.JSONField(blank=True, default=dict)),
                ('field_definitions', models.JSONField(blank=True, default=dict)),
                ('classification_hints', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('user_created', models.ForeignKey(db_column='UserCreatedUUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(db_column='UserUpdatedUUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EngineConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='JsonExt', default=dict)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='DateCreated', null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_column='DateUpdated', null=True)),
                ('version', models.IntegerField(default=1)),
                ('validity_from', models.DateTimeField(blank=True, db_column='ValidityFrom', null=True)),
                ('validity_to', models.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('name', models.CharField(max_length=255)),
                ('adapter', models.CharField(choices=[('mistral', 'Mistral'), ('gemini', 'Gemini'), ('deepseek', 'DeepSeek')], max_length=50)),
                ('endpoint_url', models.URLField(max_length=500)),
                ('api_key_encrypted', models.BinaryField(blank=True, null=True)),
                ('model_name', models.CharField(max_length=255)),
                ('deployment_mode', models.CharField(choices=[('cloud', 'Cloud'), ('self_hosted', 'Self Hosted')], default='cloud', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_fallback', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('max_tokens', models.IntegerField(default=4096)),
                ('temperature', models.FloatField(default=0.1)),
                ('timeout_seconds', models.IntegerField(default=120)),
                ('user_created', models.ForeignKey(db_column='UserCreatedUUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(db_column='UserUpdatedUUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='JsonExt', default=dict)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='DateCreated', null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_column='DateUpdated', null=True)),
                ('version', models.IntegerField(default=1)),
                ('validity_from', models.DateTimeField(blank=True, db_column='ValidityFrom', null=True)),
                ('validity_to', models.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('original_filename', models.CharField(max_length=500)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField()),
                ('storage_key', models.CharField(max_length=1000, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('preprocessing', 'Preprocessing'), ('classifying', 'Classifying'), ('extracting', 'Extracting'), ('completed', 'Completed'), ('failed', 'Failed'), ('review_required', 'Review Required')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('classification_confidence', models.FloatField(blank=True, null=True)),
                ('preprocessing_metadata', models.JSONField(blank=True, default=dict)),
                ('language', models.CharField(blank=True, help_text='ISO 639-1 language code detected during classification', max_length=10, null=True)),
                ('claim_uuid', models.UUIDField(blank=True, help_text='UUID of linked openIMIS Claim (plain UUID, not FK)', null=True)),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documents', to='claimlens.documenttype')),
                ('engine_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documents', to='claimlens.engineconfig')),
                ('user_created', models.ForeignKey(db_column='UserCreatedUUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(db_column='UserUpdatedUUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExtractionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='JsonExt', default=dict)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='DateCreated', null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_column='DateUpdated', null=True)),
                ('version', models.IntegerField(default=1)),
                ('validity_from', models.DateTimeField(blank=True, db_column='ValidityFrom', null=True)),
                ('validity_to', models.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('structured_data', models.JSONField(default=dict)),
                ('field_confidences', models.JSONField(default=dict)),
                ('aggregate_confidence', models.FloatField(default=0.0)),
                ('raw_llm_response', models.JSONField(blank=True, default=dict)),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('tokens_used', models.IntegerField(default=0)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='extraction_result', to='claimlens.document')),
                ('user_created', models.ForeignKey(db_column='UserCreatedUUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(db_column='UserUpdatedUUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='JsonExt', default=dict)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='DateCreated', null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_column='DateUpdated', null=True)),
                ('version', models.IntegerField(default=1)),
                ('validity_from', models.DateTimeField(blank=True, db_column='ValidityFrom', null=True)),
                ('validity_to', models.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('action', models.CharField(choices=[('upload', 'Upload'), ('preprocess', 'Preprocess'), ('classify', 'Classify'), ('extract', 'Extract'), ('status_change', 'Status Change'), ('review', 'Review'), ('error', 'Error')], max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='audit_logs', to='claimlens.document')),
                ('engine_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='audit_logs', to='claimlens.engineconfig')),
                ('user_created', models.ForeignKey(db_column='UserCreatedUUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(db_column='UserUpdatedUUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='DocumentMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='claimlens.document')),
                ('mutation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='claimlens_documents', to='core.mutationlog')),
            ],
            options={
                'abstract': False,
            },
        ),
        # --- New models ---
        migrations.CreateModel(
            name='EngineCapabilityScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='JsonExt', default=dict)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='DateCreated', null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_column='DateUpdated', null=True)),
                ('version', models.IntegerField(default=1)),
                ('validity_from', models.DateTimeField(blank=True, db_column='ValidityFrom', null=True)),
                ('validity_to', models.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('language', models.CharField(help_text='ISO 639-1 language code', max_length=10)),
                ('accuracy_score', models.IntegerField(default=50, help_text='Accuracy score 0-100')),
                ('cost_per_page', models.DecimalField(decimal_places=4, default=0, help_text='Cost per page in USD', max_digits=10)),
                ('speed_score', models.IntegerField(default=50, help_text='Speed score 0-100')),
                ('is_active', models.BooleanField(default=True)),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='capability_scores', to='claimlens.documenttype')),
                ('engine_config', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='capability_scores', to='claimlens.engineconfig')),
                ('user_created', models.ForeignKey(db_column='UserCreatedUUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(db_column='UserUpdatedUUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('engine_config', 'language', 'document_type')},
            },
        ),
        migrations.CreateModel(
            name='RoutingPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='JsonExt', default=dict)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='DateCreated', null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_column='DateUpdated', null=True)),
                ('version', models.IntegerField(default=1)),
                ('validity_from', models.DateTimeField(blank=True, db_column='ValidityFrom', null=True)),
                ('validity_to', models.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('accuracy_weight', models.FloatField(default=0.5)),
                ('cost_weight', models.FloatField(default=0.3)),
                ('speed_weight', models.FloatField(default=0.2)),
                ('user_created', models.ForeignKey(db_column='UserCreatedUUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(db_column='UserUpdatedUUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Routing policies',
            },
        ),
        migrations.CreateModel(
            name='ValidationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='JsonExt', default=dict)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='DateCreated', null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_column='DateUpdated', null=True)),
                ('version', models.IntegerField(default=1)),
                ('validity_from', models.DateTimeField(blank=True, db_column='ValidityFrom', null=True)),
                ('validity_to', models.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('rule_type', models.CharField(choices=[('eligibility', 'Eligibility'), ('clinical', 'Clinical'), ('fraud', 'Fraud'), ('registry', 'Registry')], max_length=20)),
                ('rule_definition', models.JSONField(blank=True, default=dict)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='warning', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('user_created', models.ForeignKey(db_column='UserCreatedUUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(db_column='UserUpdatedUUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValidationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='JsonExt', default=dict)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='DateCreated', null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_column='DateUpdated', null=True)),
                ('version', models.IntegerField(default=1)),
                ('validity_from', models.DateTimeField(blank=True, db_column='ValidityFrom', null=True)),
                ('validity_to', models.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('validation_type', models.CharField(choices=[('upstream', 'Upstream'), ('downstream', 'Downstream')], max_length=20)),
                ('overall_status', models.CharField(choices=[('matched', 'Matched'), ('mismatched', 'Mismatched'), ('partial_match', 'Partial Match'), ('pending', 'Pending'), ('error', 'Error')], default='pending', max_length=20)),
                ('field_comparisons', models.JSONField(blank=True, default=dict)),
                ('discrepancy_count', models.IntegerField(default=0)),
                ('match_score', models.FloatField(default=0.0)),
                ('summary', models.TextField(blank=True, default='')),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='validation_results', to='claimlens.document')),
                ('user_created', models.ForeignKey(db_column='UserCreatedUUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(db_column='UserUpdatedUUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValidationFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='JsonExt', default=dict)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='DateCreated', null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_column='DateUpdated', null=True)),
                ('version', models.IntegerField(default=1)),
                ('validity_from', models.DateTimeField(blank=True, db_column='ValidityFrom', null=True)),
                ('validity_to', models.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('finding_type', models.CharField(choices=[('violation', 'Violation'), ('warning', 'Warning'), ('update_proposal', 'Update Proposal')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='warning', max_length=10)),
                ('field', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('resolution_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('deferred', 'Deferred')], default='pending', max_length=20)),
                ('validation_result', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='findings', to='claimlens.validationresult')),
                ('validation_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='findings', to='claimlens.validationrule')),
                ('user_created', models.ForeignKey(db_column='UserCreatedUUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(db_column='UserUpdatedUUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegistryUpdateProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='JsonExt', default=dict)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='DateCreated', null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_column='DateUpdated', null=True)),
                ('version', models.IntegerField(default=1)),
                ('validity_from', models.DateTimeField(blank=True, db_column='ValidityFrom', null=True)),
                ('validity_to', models.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('target_model', models.CharField(help_text='e.g. insuree, health_facility', max_length=50)),
                ('target_uuid', models.UUIDField()),
                ('field_name', models.CharField(max_length=255)),
                ('current_value', models.TextField(blank=True, default='')),
                ('proposed_value', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('applied', 'Applied'), ('rejected', 'Rejected')], default='proposed', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='registry_proposals', to='claimlens.document')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='claimlens_proposal_reviews', to='core.user')),
                ('validation_result', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='registry_proposals', to='claimlens.validationresult')),
                ('user_created', models.ForeignKey(db_column='UserCreatedUUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(db_column='UserUpdatedUUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
